// <auto-generated />
using System;
using BookReviewHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookReviewHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411235604_AddAuthorEntity1")]
    partial class AddAuthorEntity1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookReviewHub.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Eric Arthur Blair, known by his pen name George Orwell, was an English novelist and essayist.",
                            BirthYear = 1903,
                            Name = "George Orwell",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Author of the Harry Potter fantasy series.",
                            BirthYear = 1965,
                            Name = "J.K. Rowling",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Best known for the Dune series of science fiction novels.",
                            BirthYear = 1920,
                            Name = "Frank Herbert",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Known for her 66 detective novels and 14 short story collections.",
                            BirthYear = 1890,
                            Name = "Agatha Christie",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Author of The Hobbit and The Lord of the Rings.",
                            BirthYear = 1892,
                            Name = "J.R.R. Tolkien",
                            Nationality = "British"
                        });
                });

            modelBuilder.Entity("BookReviewHub.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "A dystopian novel set in a totalitarian society under constant surveillance.",
                            GenreId = 3,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "An allegorical novella about farm animals who rebel against their farmer.",
                            GenreId = 1,
                            PublicationYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "A young boy discovers he is a wizard and attends Hogwarts School.",
                            GenreId = 4,
                            PublicationYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Description = "An epic sci-fi saga set on the desert planet Arrakis.",
                            GenreId = 3,
                            PublicationYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            Description = "Hercule Poirot investigates a murder aboard a luxury train.",
                            GenreId = 5,
                            PublicationYear = 1934,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            Description = "Frodo Baggins begins his quest to destroy the One Ring.",
                            GenreId = 4,
                            PublicationYear = 1954,
                            Title = "The Fellowship of the Ring"
                        });
                });

            modelBuilder.Entity("BookReviewHub.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "History"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("BookReviewHub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookReviewHub.Models.Book", b =>
                {
                    b.HasOne("BookReviewHub.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookReviewHub.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookReviewHub.Models.Review", b =>
                {
                    b.HasOne("BookReviewHub.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookReviewHub.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookReviewHub.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookReviewHub.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
